const styles = {
  dashboard: { fontFamily: 'Arial, sans-serif', fontSize: '30px', minHeight: '100vh', backgroundColor: '#f3f4f6', display: 'flex', flexDirection: 'column' },
  header: { backgroundColor: '#1f2937', color: 'white', padding: '20px 30px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { margin: 0, fontSize: '24px' },
  headerActions: { display: 'flex', alignItems: 'center', gap: '15px' },
  adminName: { fontSize: '20px' },
  nav: { backgroundColor: 'white', padding: '0 30px', display: 'flex', gap: '5px', borderBottom: '1px solid #e5e7eb',marginTop: '100px' },
  navBtn: { padding: '15px 20px', border: 'none', background: 'none', cursor: 'pointer', fontSize: '20px', fontWeight: '500', color: '#6b7280', borderBottom: '2px solid transparent', transition: 'all 0.2s' },
  navBtnActive: { color: '#4f46e5', borderBottomColor: '#4f46e5' },
  content: { padding: '30px', width: '70%', maxWidth: '90%', margin: '0 auto' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px', marginBottom: '30px' },
  statCard: { backgroundColor: 'white', padding: '20px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '15px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' },
  statIcon: { width: '50px', height: '50px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  statContent: { flex: 1 },
  statTitle: { margin: 0, fontSize: '20px', color: '#6b7280', fontWeight: '500' },
  statValue: { margin: '5px 0 0 0', fontSize: '24px', fontWeight: 'bold', color: '#1f2937' },
  recentSection: { backgroundColor: 'white', padding: '20px', borderRadius: '8px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' },
  sectionTitle: { margin: '0 0 20px 0', fontSize: '30px', fontWeight: 'bold', color: '#1f2937' },
  sectionHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '10px' },
  table: { width: '100%', borderCollapse: 'collapse', backgroundColor: 'white', borderRadius: '8px', overflow: 'hidden' },
  th: { padding: '12px', textAlign: 'left', backgroundColor: '#f9fafb', fontWeight: '600', fontSize: '13px', color: '#374151', borderBottom: '1px solid #e5e7eb' },
  td: { padding: '12px', borderBottom: '1px solid #e5e7eb', fontSize: '20px', color: '#1f2937' },
  tr: { transition: 'background-color 0.2s' },
  badge: { padding: '4px 12px', borderRadius: '12px', fontSize: '20px', fontWeight: '500', display: 'inline-block' },
  badgeCompleted: { backgroundColor: '#d1fae5', color: '#065f46' },
  badgePending: { backgroundColor: '#fef3c7', color: '#92400e' },
  badgeActive: { backgroundColor: '#dbeafe', color: '#1e40af' },
  badgeInactive: { backgroundColor: '#e5e7eb', color: '#374151' },
  badgeMonetary: { backgroundColor: '#dbeafe', color: '#1e40af' },
  badgeNonMonetary: { backgroundColor: '#fef3c7', color: '#92400e' },
  verificationBadge: { display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '4px 12px', borderRadius: '12px', fontSize: '20px', fontWeight: '500' },
  verifiedBadge: { backgroundColor: '#d1fae5', color: '#065f46' },
  btnPrimary: { padding: '10px 20px', backgroundColor: '#4f46e5', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '20px', fontWeight: '500' },
  btnSecondary: { padding: '10px 20px', backgroundColor: '#e5e7eb', color: '#374151', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '20px', fontWeight: '500' },
  btnIcon: { padding: '6px', backgroundColor: 'transparent', border: 'none', cursor: 'pointer', color: '#6b7280', display: 'inline-flex', alignItems: 'center' },
  btnIconDelete: { color: '#ef4444' },
  btnLink: { padding: '4px 8px', backgroundColor: 'transparent', border: 'none', cursor: 'pointer', color: '#4f46e5', fontSize: '20px', textDecoration: 'underline' },
  actionButtons: { display: 'flex', gap: '8px' },
  searchBar: { padding: '10px 15px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '20px', width: '100%', maxWidth: '300px' },
  filterContainer: { display: 'flex', gap: '10px', alignItems: 'center', flexWrap: 'wrap' },
  filterLabel: { fontSize: '20px', fontWeight: '500', color: '#374151' },
  select: { padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '20px' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modalContent: { backgroundColor: 'white', borderRadius: '8px', width: '90%', maxWidth: '500px', maxHeight: '90vh', overflow: 'auto' },
  modalHeader: { padding: '20px', borderBottom: '1px solid #e5e7eb', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  modalTitle: { margin: 0, fontSize: '18px', fontWeight: 'bold' },
  closeBtn: { padding: '4px', backgroundColor: 'transparent', border: 'none', cursor: 'pointer', color: '#6b7280' },
  modalBody: { padding: '20px' },
  formGroup: { marginBottom: '15px' },
  label: { display: 'block', marginBottom: '5px', fontSize: '20px', fontWeight: '500', color: '#374151' },
  input: { width: '100%', padding: '10px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '20px', boxSizing: 'border-box' },
  formActions: { display: 'flex', gap: '10px', justifyContent: 'flex-end', marginTop: '20px' },
  documentList: { display: 'flex', flexDirection: 'column', gap: '10px' },
  documentItem: { padding: '12px', border: '1px solid #e5e7eb', borderRadius: '6px', display: 'flex', alignItems: 'center', gap: '10px' },
  docName: { flex: 1, fontSize: '20px' }
};

export default styles;