const styles = {
  dashboard: { maxWidth: '1400px', margin: '0 auto', padding: '20px' },
  dashboardHeader: { background: 'white', borderRadius: '16px', padding: '32px', marginBottom: '24px', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' },
  headerContent: { textAlign: 'center' },
  dashboardTitle: { fontSize: '32px', fontWeight: '700', color: '#1f2937', marginBottom: '8px' },
  dashboardSubtitle: { fontSize: '16px', color: '#6b7280' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px', marginBottom: '24px', marginTop: '12%' },
  statCard: { background: 'white', borderRadius: '12px', padding: '24px', display: 'flex', alignItems: 'center', gap: '16px', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.08)' },
  statIcon: { width: '56px', height: '56px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' },
  monetaryIcon: { background: 'linear-gradient(135deg, #8b5cf6, #7c3aed)' },
  activeIcon: { background: 'linear-gradient(135deg, #f59e0b, #d97706)' },
  completedIcon: { background: 'linear-gradient(135deg, #3b82f6, #2563eb)' },
  sentIcon: { background: 'linear-gradient(135deg, #10b981, #059669)' },
  statContent: { flex: 1 },
  statLabel: { fontSize: '14px', color: '#6b7280', marginBottom: '4px' },
  statValue: { fontSize: '24px', fontWeight: '700', color: '#1f2937' },
  tabsContainer: { background: 'white', borderRadius: '12px', padding: '8px', marginBottom: '24px', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.08)' },
  tabs: { display: 'flex', gap: '8px' },
  tab: { flex: 1, padding: '16px 24px', border: 'none', background: 'transparent', borderRadius: '8px', fontSize: '16px', fontWeight: '600', color: '#6b7280', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' },
  activeTab: { background: 'linear-gradient(135deg, #667eea, #764ba2)', color: 'white' },
  filtersContainer: { background: 'white', borderRadius: '12px', padding: '20px 24px', marginBottom: '24px', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.08)' },
  filterHeader: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px', color: '#374151' },
  filterTitle: { fontSize: '16px', fontWeight: '600' },
  filterButtons: { display: 'flex', flexWrap: 'wrap', gap: '12px' },
  filterBtn: { padding: '10px 20px', border: '2px solid #e5e7eb', background: 'white', borderRadius: '8px', fontSize: '14px', fontWeight: '600', color: '#6b7280', cursor: 'pointer', transition: 'all 0.2s' },
  filterBtnActive: { background: '#667eea', borderColor: '#667eea', color: 'white' },
  donationsContainer: { background: 'white', borderRadius: '16px', padding: '24px', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)', minHeight: '300px' },
  emptyState: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '60px 20px', gap: '16px' },
  emptyText: { fontSize: '18px', color: '#6b7280', fontWeight: '500' },
  donationsList: { display: 'grid', gap: '20px' },
  donationCard: { border: '2px solid #e5e7eb', borderRadius: '12px', overflow: 'hidden' },
  cardHeader: { background: 'linear-gradient(135deg, #f9fafb, #f3f4f6)', padding: '20px 24px', borderBottom: '2px solid #e5e7eb' },
  cardTitleSection: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' },
  cardTitle: { fontSize: '20px', fontWeight: '700', color: '#1f2937' },
  statusBadge: { padding: '6px 16px', borderRadius: '20px', fontSize: '12px', fontWeight: '700', color: 'white', letterSpacing: '0.5px' },
  cardDate: { fontSize: '14px', color: '#6b7280' },
  cardBody: { padding: '24px' },
  detailsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '24px', marginBottom: '24px', paddingBottom: '24px', borderBottom: '2px solid #f3f4f6' },
  detailSection: { display: 'flex', flexDirection: 'column', gap: '4px' },
  detailLabel: { fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase', letterSpacing: '0.5px' },
  detailValue: { fontSize: '18px', fontWeight: '600', color: '#1f2937' },
  detailContact: { fontSize: '14px', color: '#6b7280' },
  amountSection: { display: 'flex', justifyContent: 'space-around', marginBottom: '20px', padding: '16px', background: '#f9fafb', borderRadius: '8px' },
  amountInfo: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px' },
  amountLabel: { fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' },
  amountValue: { fontSize: '20px', fontWeight: '700', color: '#1f2937' },
  itemsSection: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', padding: '16px', background: '#f9fafb', borderRadius: '8px' },
  itemsInfo: { display: 'flex', alignItems: 'center', gap: '12px', color: '#667eea' },
  itemsText: { fontSize: '18px', fontWeight: '600', color: '#1f2937' },
  quantityInfo: { display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '4px' },
  quantityLabel: { fontSize: '12px', fontWeight: '600', color: '#6b7280', textTransform: 'uppercase' },
  quantityValue: { fontSize: '20px', fontWeight: '700', color: '#1f2937' },
  progressSection: { marginBottom: '20px' },
  progressBar: { width: '100%', height: '12px', background: '#e5e7eb', borderRadius: '6px', overflow: 'hidden', marginBottom: '8px' },
  progressFill: { height: '100%', transition: 'width 0.3s ease', borderRadius: '6px' },
  progressText: { fontSize: '14px', color: '#6b7280', fontWeight: '600' },
  completeBtn: { width: '100%', padding: '14px 24px', background: 'linear-gradient(135deg, #3b82f6, #2563eb)', color: 'white', border: 'none', borderRadius: '8px', fontSize: '16px', fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', marginBottom: '10px' },
  sentBtn: { width: '100%', padding: '14px 24px', background: 'linear-gradient(135deg, #10b981, #059669)', color: 'white', border: 'none', borderRadius: '8px', fontSize: '16px', fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' },
};

export default styles;